SELECT 
    C.CAR_ID,
    C.CAR_TYPE,
    ROUND(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON C.CAR_TYPE = P.CAR_TYPE
WHERE P.DURATION_TYPE LIKE '30%' 
AND ROUND(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100) BETWEEN 500000 AND 2000000
AND c.car_type in ('세단', 'SUV')
AND c.car_id not in (
    SELECT car_id
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    WHERE H.CAR_ID = C.CAR_ID
      AND H.START_DATE < '2022-12-01'
      AND H.END_DATE >= '2022-11-01'
)
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC;