# select YEAR(DIFFERENTIATION_DATE) as YEAR, (
#     select max(SIZE_OF_COLONY) from ecoli_data where YEAR(DIFFERENTIATION_DATE) = YEAR
# ) - SIZE_OF_COLONY as YEAR_DEV, ID
# from ecoli_data
# order by YEAR, YEAR_DEV


# SELECT 
#     YEAR(DIFFERENTIATION_DATE) AS YEAR, 
#     (MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY) AS YEAR_DEV, 
#     ID
# FROM 
#     ECOLI_DATA
# ORDER BY 
#     YEAR ASC, 
#     YEAR_DEV ASC;

select YEAR(DIFFERENTIATION_DATE) as YEAR, 
(MAX(SIZE_OF_COLONY) OVER(PARTITION BY YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY) as YEAR_DEV,
ID
from ecoli_data
ORDER BY 
    YEAR ASC, 
    YEAR_DEV ASC;